# Generated by Django 5.0.1 on 2024-02-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', 'Peut changer le titre d’un billet de blog')]},
        ),
    ]
